// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"2D_Cat_OpenWebInTheGame","status":true,"description":"v1.0 在游戏内打开网站页面。","parameters":{}},
{"name":"2D_Cat_SkipMovieInTheGame","status":true,"description":"v1.1 随时跳出正在播放的影像，并可显示影像播放倒计时。","parameters":{"isClickScreenSkip":"true","isPressEscSkip":"true","isOnTouchSkip":"true","isShowCountdownText":"true"}},
{"name":"TorigoyaMZ_Bookshelf","status":true,"description":"文本书架书籍系统(v.1.2.1)","parameters":{"base":"","bookshelfTitleFontSize":"22","bookshelfWidth":"400","bookshelfMaxHeight":"0","bookContentFontSize":"24","bookContentWidth":"0","bookContentHeight":"0","menu":"","menuItems":"[\"{\\\"name\\\":\\\"明信片\\\",\\\"fileName\\\":\\\"mingxinpian\\\",\\\"switchId\\\":\\\"0\\\",\\\"visibility\\\":\\\"true\\\",\\\"note\\\":\\\"\\\"}\",\"{\\\"name\\\":\\\"日记\\\",\\\"fileName\\\":\\\"riji\\\",\\\"switchId\\\":\\\"0\\\",\\\"visibility\\\":\\\"true\\\",\\\"note\\\":\\\"\\\"}\"]"}},
{"name":"拼图/ASJigsawGame","status":true,"description":"【V1.0.2】拼图小游戏","parameters":{}},
{"name":"拼图/ASSpritePictureExtend","status":true,"description":"[V1.0.0] 显示图片功能扩展插件","parameters":{"cancelButtonOffsetX":"0","cancelButtonOffsetY":"0","showCancelButtonPictureIDList":"[]"}}
];
